services:
  - type: web
    name: APP-FINAL
    rootDir: APP-FINAL
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
